//! The 144-entry env-object table of the original (`CEnvObjectManager`, 0x20 bytes per entry, ghidra 0xD7AA88).
//! Extracted from libABK291.so with an ELF reader (helper name -> model / anim / smackable type / flags).
//! Word meaning (from `GetSmackableTypeFromEnvObjectType @001e1db0`, `GetEnvObjectTypeFromHelperName @001e1dec`,
//! `LoadEnvObject @001e29b8`): +0 name, +4 model path, +8 anim path, +0xC smackable type (0x7e = none), the rest are flag words
//! (`w4`..`w7`) whose individual meaning is not decoded (UNRESOLVED: names of w4..w7).
//! Model paths use the asset-path prefixes `ENVOBJ:` (pak/envobjects) and `MODELTHEME:` (the track theme's models.pak).

#[derive(Debug, Clone, Copy)]
pub struct EnvObj {
    pub name: &'static str,
    pub model: Option<&'static str>,
    pub anim: Option<&'static str>,
    /// index into the smackable definitions, 0x7e = not a smackable
    pub smackable: u32,
    pub w4: u32,
    pub w5: u32,
    pub w6: bool,
    pub w7: bool,
}

pub const NO_SMACKABLE: u32 = 0x7e;

pub static ENV_OBJECTS: [EnvObj; 144] = [
    EnvObj { name: "smck_blocks_glass_long", model: None, anim: None, smackable: 0x0, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_glass_thick", model: None, anim: None, smackable: 0x1, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_glass_frag01", model: None, anim: None, smackable: 0x2, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_glass_frag02", model: None, anim: None, smackable: 0x2, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_glass_frag03", model: None, anim: None, smackable: 0x2, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_glass_frag04", model: None, anim: None, smackable: 0x2, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_stone_long", model: None, anim: None, smackable: 0x6, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_stone_thick", model: None, anim: None, smackable: 0x7, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_wood_long", model: None, anim: None, smackable: 0x8, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_wood_thick", model: None, anim: None, smackable: 0x9, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_tnt_box", model: None, anim: None, smackable: 0xa, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_tnt_frag01", model: None, anim: None, smackable: 0xb, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_tnt_frag02", model: None, anim: None, smackable: 0xc, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_tnt_frag03", model: None, anim: None, smackable: 0xd, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_tnt_frag04", model: None, anim: None, smackable: 0xe, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_tnt_frag05", model: None, anim: None, smackable: 0xf, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_wood_large_boulder", model: None, anim: None, smackable: 0x10, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_stone_large_tri", model: None, anim: None, smackable: 0x11, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_wood_large_frame", model: None, anim: None, smackable: 0x12, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_pig", model: None, anim: None, smackable: 0x13, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_logger", model: Some("ENVOBJ:logger.XGM"), anim: None, smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_block", model: Some("ENVOBJ:block.XGM"), anim: Some("ENVOBJ:block.XGA"), smackable: 0x7e, w4: 0x28, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_startlineT002R000", model: Some("ENVOBJ:Cobalt Plateau/startlineT002R000.XGM"), anim: Some("ENVOBJ:Cobalt Plateau/Anims/startlineT002R000_loop.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_finishlineT002R000", model: Some("ENVOBJ:Cobalt Plateau/finishlineT002R000.XGM"), anim: Some("ENVOBJ:Cobalt Plateau/Anims/finishlineT002R000_loop.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_splitgateAT002R000", model: Some("ENVOBJ:Cobalt Plateau/splitgateAT002R000.XGM"), anim: Some("ENVOBJ:Cobalt Plateau/Anims/splitgateAT002R000_loop.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_splitgateBT002R000", model: Some("ENVOBJ:Cobalt Plateau/splitgateBT002R000.XGM"), anim: Some("ENVOBJ:Cobalt Plateau/Anims/splitgateBT002R000_loop.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_pirateshipT002R000", model: Some("ENVOBJ:Cobalt Plateau/pirateshipT002R000.XGM"), anim: Some("ENVOBJ:Cobalt Plateau/Anims/pirateshipT002R000_loop.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_seatingAT002R000", model: Some("ENVOBJ:Cobalt Plateau/seatingAT002R000.XGM"), anim: Some("ENVOBJ:Cobalt Plateau/Anims/seatingAT002R000_loop.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_seatingBT002R000", model: Some("ENVOBJ:Cobalt Plateau/seatingBT002R000.XGM"), anim: Some("ENVOBJ:Cobalt Plateau/Anims/seatingBT002R000_loop.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "slingshot", model: Some("ENVOBJ:slingshot.XGM"), anim: None, smackable: 0x7e, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "slingshot_jenga", model: Some("ENVOBJ:slingshot_jenga.XGM"), anim: None, smackable: 0x7e, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "slingshot_king", model: Some("ENVOBJ:slingshot_king.XGM"), anim: None, smackable: 0x7e, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "smck_blocks_glass_tall", model: None, anim: None, smackable: 0x14, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_glass_1msquare", model: None, anim: None, smackable: 0x15, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_stone_tall", model: None, anim: None, smackable: 0x16, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_stone_slab", model: None, anim: None, smackable: 0x17, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_wood_tall", model: None, anim: None, smackable: 0x18, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_wood_short", model: None, anim: None, smackable: 0x19, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_blocks_wood_slab", model: None, anim: None, smackable: 0x1a, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "!invalid!", model: Some("ENVOBJ:Distance_Marker.XGM"), anim: None, smackable: 0x7e, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "!invalid!", model: Some("ENVOBJ:star1.XGM"), anim: None, smackable: 0x7e, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "!invalid!", model: Some("ENVOBJ:star2.XGM"), anim: None, smackable: 0x7e, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "!invalid!", model: Some("ENVOBJ:star3.XGM"), anim: None, smackable: 0x7e, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_rectb", model: None, anim: None, smackable: 0x1c, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_frag1f", model: None, anim: None, smackable: 0x1d, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_frag2f", model: None, anim: None, smackable: 0x1e, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_frag3f", model: None, anim: None, smackable: 0x1f, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_frag4f", model: None, anim: None, smackable: 0x20, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_frag5f", model: None, anim: None, smackable: 0x21, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_1_5m_sq", model: None, anim: None, smackable: 0x22, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_1_5m_sq", model: None, anim: None, smackable: 0x23, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_1_5m_sq", model: None, anim: None, smackable: 0x24, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_stone_frag", model: None, anim: None, smackable: 0x25, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_glass_frag", model: None, anim: None, smackable: 0x26, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "smck_wood_frag", model: None, anim: None, smackable: 0x27, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_6m_wide", model: None, anim: None, smackable: 0x28, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_5m_sq", model: None, anim: None, smackable: 0x29, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_5m_sq", model: None, anim: None, smackable: 0x2a, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_5m_sq", model: None, anim: None, smackable: 0x2b, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_tnt_box_5m", model: None, anim: None, smackable: 0x2c, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_3m_sq", model: None, anim: None, smackable: 0x2d, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_3m_sq", model: None, anim: None, smackable: 0x2e, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_3m_sq", model: None, anim: None, smackable: 0x2f, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_tnt_box_3m", model: None, anim: None, smackable: 0x30, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_tnt_box_large", model: None, anim: None, smackable: 0x31, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_PiratePig1_3m", model: None, anim: None, smackable: 0x32, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_PiratePig2_3m", model: None, anim: None, smackable: 0x33, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_1x4", model: None, anim: None, smackable: 0x34, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_1x8", model: None, anim: None, smackable: 0x35, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_1x10", model: None, anim: None, smackable: 0x36, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_2x2", model: None, anim: None, smackable: 0x37, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_2x4", model: None, anim: None, smackable: 0x38, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_2x6", model: None, anim: None, smackable: 0x39, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_4x4", model: None, anim: None, smackable: 0x3a, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_4x4Tri", model: None, anim: None, smackable: 0x3b, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_1x4", model: None, anim: None, smackable: 0x3c, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_1x8", model: None, anim: None, smackable: 0x3d, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_1x10", model: None, anim: None, smackable: 0x3e, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_2x2", model: None, anim: None, smackable: 0x3f, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_2x4", model: None, anim: None, smackable: 0x40, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_2x6", model: None, anim: None, smackable: 0x41, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_4x4", model: None, anim: None, smackable: 0x42, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_4x4Tri", model: None, anim: None, smackable: 0x43, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_1x4", model: None, anim: None, smackable: 0x44, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_1x8", model: None, anim: None, smackable: 0x45, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_1x10", model: None, anim: None, smackable: 0x46, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_2x2", model: None, anim: None, smackable: 0x47, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_2x4", model: None, anim: None, smackable: 0x48, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_2x6", model: None, anim: None, smackable: 0x49, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_4x4", model: None, anim: None, smackable: 0x4a, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_4x4Tri", model: None, anim: None, smackable: 0x4b, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_cannon", model: Some("MODELTHEME:Cannon.XGM"), anim: Some("MODELTHEME:Animations/Cannon_Fire.xga"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_cannon_ball", model: None, anim: None, smackable: 0x4d, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_Pig_3m", model: Some("MODELTHEME:gameplay_Pig_3m.XGM"), anim: Some("MODELTHEME:Animations/Pig_CannonFireman.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_Pig_3m_1", model: Some("MODELTHEME:gameplay_Pig_3m_1.XGM"), anim: Some("MODELTHEME:Animations/Pig_CannonWatchman.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_PiratePig1_3m", model: Some("MODELTHEME:gameplay_PiratePig1_3m.XGM"), anim: Some("MODELTHEME:Animations/PiratePig1_idle.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_PiratePig2_3m_1", model: Some("MODELTHEME:gameplay_PiratePig2_3m_1.XGM"), anim: Some("MODELTHEME:Animations/PiratePig2_1_idle.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_PiratePig2_3m_2", model: Some("MODELTHEME:gameplay_PiratePig2_3m_2.XGM"), anim: Some("MODELTHEME:Animations/PiratePig2_2_idle.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_PiratePig2_3m_3", model: Some("MODELTHEME:gameplay_PiratePig2_3m_3.XGM"), anim: Some("MODELTHEME:Animations/PiratePig2_3_idle.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_PiratePig2_3m_4", model: Some("MODELTHEME:gameplay_PiratePig2_3m_4.XGM"), anim: Some("MODELTHEME:Animations/PiratePig2_4_idle.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_PiratePig2_3m_5", model: Some("MODELTHEME:gameplay_PiratePig2_3m_5.XGM"), anim: Some("MODELTHEME:Animations/PiratePig2_CannonFireman.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_PiratePig2_3m_6", model: Some("MODELTHEME:gameplay_PiratePig2_3m_6.XGM"), anim: Some("MODELTHEME:Animations/PiratePig2_CannonWatchman.XGA"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_boat_001", model: Some("MODELTHEME:gameplay_boat_001.xgm"), anim: None, smackable: 0x7e, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_3X6_h", model: None, anim: None, smackable: 0x4e, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_glass_3X6_w", model: None, anim: None, smackable: 0x4f, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_3X6_h", model: None, anim: None, smackable: 0x50, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_stone_3X6_w", model: None, anim: None, smackable: 0x51, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_3X6_h", model: None, anim: None, smackable: 0x52, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_block_wood_3X6_w", model: None, anim: None, smackable: 0x53, w4: 0x1, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "smck_route_blocker", model: None, anim: None, smackable: 0x5d, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "smck_blocker_sml", model: None, anim: None, smackable: 0x5e, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "smck_blocker_lrg", model: None, anim: None, smackable: 0x5f, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "smck_blocker_seedway2", model: None, anim: None, smackable: 0x60, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "smck_blocker_air1_a", model: None, anim: None, smackable: 0x61, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "smck_blocker_air1_b", model: None, anim: None, smackable: 0x62, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "smck_blocker_snow_a", model: None, anim: None, smackable: 0x6b, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "smck_blocker_snow_a", model: None, anim: None, smackable: 0x6b, w4: 0x1, w5: 0x0, w6: true, w7: false },
    EnvObj { name: "slalom_post_blue_left", model: None, anim: None, smackable: 0x6d, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_blue_left_frag01", model: None, anim: None, smackable: 0x6e, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_blue_left_frag02", model: None, anim: None, smackable: 0x6f, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_blue_left_frag03", model: None, anim: None, smackable: 0x70, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_blue_right", model: None, anim: None, smackable: 0x71, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_blue_right_frag01", model: None, anim: None, smackable: 0x72, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_blue_right_frag02", model: None, anim: None, smackable: 0x73, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_blue_right_frag03", model: None, anim: None, smackable: 0x74, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_red_left", model: None, anim: None, smackable: 0x75, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_red_left_frag01", model: None, anim: None, smackable: 0x76, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_red_left_frag02", model: None, anim: None, smackable: 0x77, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_red_left_frag03", model: None, anim: None, smackable: 0x78, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_red_right", model: None, anim: None, smackable: 0x79, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_red_right_frag01", model: None, anim: None, smackable: 0x7a, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_red_right_frag02", model: None, anim: None, smackable: 0x7b, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "slalom_post_red_right_frag03", model: None, anim: None, smackable: 0x7c, w4: 0x1, w5: 0x0, w6: false, w7: true },
    EnvObj { name: "animgeo_cablecar01t006r001", model: Some("MODELTHEME:animgeo_cablecar01t006r001.xgm"), anim: Some("MODELTHEME:Animations/animgeo_cablecar01t006r001.xga"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_cablecar02t006r001", model: Some("MODELTHEME:animgeo_cablecar01t006r001.xgm"), anim: Some("MODELTHEME:Animations/animgeo_cablecar02t006r001.xga"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_cablecar03t006r001", model: Some("MODELTHEME:animgeo_cablecar01t006r001.xgm"), anim: Some("MODELTHEME:Animations/animgeo_cablecar03t006r001.xga"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_cablecar04t006r001", model: Some("MODELTHEME:animgeo_cablecar01t006r001.xgm"), anim: Some("MODELTHEME:Animations/animgeo_cablecar04t006r001.xga"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_train01T006R002", model: Some("MODELTHEME:animgeo_trainT006R002.xgm"), anim: Some("MODELTHEME:Animations/animgeo_train01T006R002.xga"), smackable: 0x7e, w4: 0x48, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_ferriswheelT006R002", model: Some("MODELTHEME:animgeo_ferriswheelT006R002.xgm"), anim: Some("MODELTHEME:Animations/animgeo_ferriswheelT006R002.xga"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_merrygoroundT006R002", model: Some("MODELTHEME:animgeo_merrygoroundT006R002.xgm"), anim: Some("MODELTHEME:Animations/animgeo_merrygoroundT006R002.xga"), smackable: 0x7e, w4: 0x48, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_helicoptor01T006R003", model: Some("MODELTHEME:animgeo_helicoptorT006R003.xgm"), anim: Some("MODELTHEME:Animations/animgeo_helicoptor01T006R003.xga"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_helicoptor02T006R003", model: Some("MODELTHEME:animgeo_helicoptorT006R003.xgm"), anim: Some("MODELTHEME:Animations/animgeo_helicoptor02T006R003.xga"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "animgeo_helicoptor03T006R003", model: Some("MODELTHEME:animgeo_helicoptorT006R003.xgm"), anim: Some("MODELTHEME:Animations/animgeo_helicoptor03T006R003.xga"), smackable: 0x7e, w4: 0x8, w5: 0x0, w6: false, w7: false },
    EnvObj { name: "gameplay_photomodel_pos", model: Some("ENVOBJ:CameraSign.xgm"), anim: None, smackable: 0x7e, w4: 0x1, w5: 0x0, w6: false, w7: false },
];

/// `GetEnvObjectTypeFromHelperName @001e1dec`: exact (case-insensitive) match first, else the first entry whose name partially matches.
/// When several entries share a name the original picks one at random; this returns the first (UNRESOLVED: random choice, only
/// `smck_blocker_snow_a` is duplicated and both entries share smackable type 0x6b).
pub fn env_object_for_helper(name: &str) -> Option<usize> {
    if let Some(i) = ENV_OBJECTS.iter().position(|e| e.name.eq_ignore_ascii_case(name)) {
        return Some(i);
    }
    ENV_OBJECTS.iter().position(|e| partial_match_nocase(name, e.name))
}

/// `StringPartialMatchNoCase @002c0474`: true when `prefix` (the second argument) is a case-insensitive prefix of `s`
/// (the loop ends with "match" as soon as the second string hits its NUL).
pub fn partial_match_nocase(s: &str, prefix: &str) -> bool {
    s.len() >= prefix.len() && s.as_bytes()[..prefix.len()].eq_ignore_ascii_case(prefix.as_bytes())
}
