//! The 126-entry smackable type table of the original (`CSmackableManager`, 0x40 bytes per entry, ghidra 0xDAD720), dumped from libABK291.so
//! with an ELF reader. There is no smackable xml: everything is this compiled table (see `LoadSmackable @001d8598`,
//! `CSmackable::Init @001d7134`, `CSmackable::Update @001d5db4`, `GetSmackableBounty @001d98a8`, `GetSmackableAlwaysCollide @001d9940`).
//!
//! Field meaning (as decoded by the research pass; "inferred" where no reader/consumer was found):
//!  * `mass`: passed to `CXGSPhys::AddRigidBody` (inferred from the only non-constant float);
//!  * `bounty`: `GetSmackableBounty`, 10 everywhere; `CSmackable::GetBounty` has no callers, so it never reaches the score;
//!  * `smash_threshold` (this+0x1160): the smackable breaks when the accumulated hit magnitude exceeds it (+inf = never);
//!  * `explosion` (this+0x1168): explosion strength applied to nearby rigid bodies when it breaks (0 = none);
//!  * `restitution` (body+0x84, inferred: 0.2 glass, 0.4 stone, 0.7 wood, 1.0 pigs);
//!  * `w6`: no reader found (block size scale / 25 on boss boxes);
//!  * `car_only` (this+0x1170): only hits by a car that has a player attached count;
//!  * `smash_fx` / `explosion_fx`: effect xml (`GetSmackableSmashFX` / `GetSmackableExplosionFX`);
//!  * `sound_type`: 1 glass 2 stone 3 terence rock 4 wood 5 TNT 6 bomb 7 cannonball 8 random power box 9 pig 10 matilda egg;
//!  * `disable_collisions`: `DisableCollisions @001d98c0` (0 everywhere);
//!  * `preload`: set for fragment sub-types the manager loads with their parent;
//!  * `always_collide`: `GetSmackableAlwaysCollide`; collides even while the car's non-collide timer runs (route / snow blockers).

#[derive(Debug, Clone, Copy)]
pub struct SmackableDef {
    pub name: &'static str,
    pub mass: f32,
    pub bounty: u32,
    pub smash_threshold: f32,
    pub explosion: f32,
    pub restitution: f32,
    pub w6: f32,
    pub car_only: bool,
    pub smash_fx: &'static str,
    pub explosion_fx: &'static str,
    pub sound_type: u32,
    pub disable_collisions: u32,
    pub w12: u32,
    pub preload: u32,
    pub always_collide: bool,
}

pub const NONE: u32 = 0x7e;

pub static SMACKABLES: [SmackableDef; 126] = [
    SmackableDef { name: "smck_blocks_glass_long", mass: 400.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 0
    SmackableDef { name: "smck_blocks_glass_thick", mass: 200.0, bounty: 10, smash_threshold: 144.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 1
    SmackableDef { name: "smck_blocks_glass_frag01", mass: 50.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 2
    SmackableDef { name: "smck_blocks_glass_frag02", mass: 50.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 3
    SmackableDef { name: "smck_blocks_glass_frag03", mass: 50.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 4
    SmackableDef { name: "smck_blocks_glass_frag04", mass: 50.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 5
    SmackableDef { name: "smck_blocks_stone_long", mass: 800.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.4, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 6
    SmackableDef { name: "smck_blocks_stone_thick", mass: 400.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.4, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 7
    SmackableDef { name: "smck_blocks_wood_long", mass: 120.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 8
    SmackableDef { name: "smck_blocks_wood_thick", mass: 60.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 9
    SmackableDef { name: "smck_tnt_box", mass: 80.0, bounty: 10, smash_threshold: 120.0, explosion: 80.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "destructible/vfx_tnt_explosion.xml", sound_type: 5, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 10
    SmackableDef { name: "smck_tnt_frag01", mass: 16.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 11
    SmackableDef { name: "smck_tnt_frag02", mass: 16.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 12
    SmackableDef { name: "smck_tnt_frag03", mass: 16.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 13
    SmackableDef { name: "smck_tnt_frag04", mass: 16.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 14
    SmackableDef { name: "smck_tnt_frag05", mass: 16.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 15
    SmackableDef { name: "smck_wood_large_boulder", mass: 200.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 16
    SmackableDef { name: "smck_stone_large_tri", mass: 600.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.4, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 17
    SmackableDef { name: "smck_wood_large_frame", mass: 200.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 18
    SmackableDef { name: "smck_pig", mass: 50.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 19
    SmackableDef { name: "smck_blocks_glass_tall", mass: 150.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 20
    SmackableDef { name: "smck_blocks_glass_1msquare", mass: 50.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 21
    SmackableDef { name: "smck_blocks_stone_tall", mass: 500.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.4, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 22
    SmackableDef { name: "smck_blocks_stone_slab", mass: 500.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.4, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 23
    SmackableDef { name: "smck_blocks_wood_tall", mass: 200.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 24
    SmackableDef { name: "smck_blocks_wood_short", mass: 100.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 25
    SmackableDef { name: "smck_blocks_wood_slab", mass: 200.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 26
    SmackableDef { name: "", mass: 6.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.5, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 27
    SmackableDef { name: "smck_block_stone_rectb", mass: 1000.0, bounty: 10, smash_threshold: 960.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 28
    SmackableDef { name: "smck_block_stone_frag1f", mass: 200.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 29
    SmackableDef { name: "smck_block_stone_frag2f", mass: 200.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 30
    SmackableDef { name: "smck_block_stone_frag3f", mass: 200.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 31
    SmackableDef { name: "smck_block_stone_frag4f", mass: 200.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 32
    SmackableDef { name: "smck_block_stone_frag5f", mass: 200.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 33
    SmackableDef { name: "smck_block_stone_1_5m_sq", mass: 500.0, bounty: 10, smash_threshold: 480.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 34
    SmackableDef { name: "smck_block_glass_1_5m_sq", mass: 60.0, bounty: 10, smash_threshold: 57.600002, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 35
    SmackableDef { name: "smck_block_wood_1_5m_sq", mass: 100.0, bounty: 10, smash_threshold: 96.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 36
    SmackableDef { name: "smck_stone_frag", mass: 7.5, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.4, w6: 0.1, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 37
    SmackableDef { name: "smck_glass_frag", mass: 2.5, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.1, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 38
    SmackableDef { name: "smck_wood_frag", mass: 5.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 0.1, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 39
    SmackableDef { name: "smck_block_stone_6m_wide", mass: 500.0, bounty: 10, smash_threshold: 480.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 40
    SmackableDef { name: "smck_block_stone_5m_sq", mass: 19000.0, bounty: 10, smash_threshold: 18240.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 41
    SmackableDef { name: "smck_block_glass_5m_sq", mass: 2280.0, bounty: 10, smash_threshold: 2188.8003, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 42
    SmackableDef { name: "smck_block_wood_5m_sq", mass: 3800.0, bounty: 10, smash_threshold: 3648.0002, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 43
    SmackableDef { name: "smck_tnt_box_5m", mass: 3040.0, bounty: 10, smash_threshold: 4560.0, explosion: 3040.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "destructible/vfx_tnt_explosion.xml", sound_type: 0, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 44
    SmackableDef { name: "smck_block_stone_3m_sq", mass: 126.5625, bounty: 10, smash_threshold: 60750.0, explosion: 0.0, restitution: 0.4, w6: 0.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 45
    SmackableDef { name: "smck_block_glass_3m_sq", mass: 42.1875, bounty: 10, smash_threshold: 20250.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 46
    SmackableDef { name: "smck_block_wood_3m_sq", mass: 84.375, bounty: 10, smash_threshold: 40500.0, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 47
    SmackableDef { name: "smck_TNT_Box_3m", mass: 84.375, bounty: 10, smash_threshold: 60.0, explosion: 90.0, restitution: 0.7, w6: 0.0, car_only: true, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "destructible/vfx_tnt_explosion.xml", sound_type: 5, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 48
    SmackableDef { name: "smck_TNT_Box_Large", mass: 84.375, bounty: 10, smash_threshold: 240.0, explosion: 100.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "destructible/vfx_tnt_explosion.xml", sound_type: 5, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 49
    SmackableDef { name: "smck_PiratePig1_3m", mass: 50.0, bounty: 10, smash_threshold: 600.0, explosion: 0.0, restitution: 1.0, w6: 0.0, car_only: false, smash_fx: "destructible/Death_Pig.xml", explosion_fx: "", sound_type: 9, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 50
    SmackableDef { name: "smck_PiratePig2_3m", mass: 50.0, bounty: 10, smash_threshold: 600.0, explosion: 0.0, restitution: 1.0, w6: 0.0, car_only: false, smash_fx: "destructible/Death_Pig.xml", explosion_fx: "", sound_type: 9, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 51
    SmackableDef { name: "smck_block_glass_1x4", mass: 25.0, bounty: 10, smash_threshold: 96.0, explosion: 0.0, restitution: 0.2, w6: 1.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 52
    SmackableDef { name: "smck_block_glass_1x8", mass: 50.0, bounty: 10, smash_threshold: 192.0, explosion: 0.0, restitution: 0.2, w6: 2.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 53
    SmackableDef { name: "smck_block_glass_1x10", mass: 62.5, bounty: 10, smash_threshold: 240.0, explosion: 0.0, restitution: 0.2, w6: 2.5, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 54
    SmackableDef { name: "smck_block_glass_2x2", mass: 25.0, bounty: 10, smash_threshold: 96.0, explosion: 0.0, restitution: 0.2, w6: 1.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 55
    SmackableDef { name: "smck_block_glass_2x4", mass: 50.0, bounty: 10, smash_threshold: 192.0, explosion: 0.0, restitution: 0.2, w6: 2.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 56
    SmackableDef { name: "smck_block_glass_2x6", mass: 75.0, bounty: 10, smash_threshold: 288.0, explosion: 0.0, restitution: 0.2, w6: 3.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 57
    SmackableDef { name: "smck_block_glass_4x4", mass: 100.0, bounty: 10, smash_threshold: 384.0, explosion: 0.0, restitution: 0.2, w6: 4.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 58
    SmackableDef { name: "smck_block_glass_4x4Tri", mass: 50.0, bounty: 10, smash_threshold: 192.0, explosion: 0.0, restitution: 0.2, w6: 2.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 59
    SmackableDef { name: "smck_block_stone_1x4", mass: 75.0, bounty: 10, smash_threshold: 576.0, explosion: 0.0, restitution: 0.4, w6: 1.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 60
    SmackableDef { name: "smck_block_stone_1x8", mass: 150.0, bounty: 10, smash_threshold: 1152.0, explosion: 0.0, restitution: 0.4, w6: 2.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 61
    SmackableDef { name: "smck_block_stone_1x10", mass: 187.5, bounty: 10, smash_threshold: 1440.0001, explosion: 0.0, restitution: 0.4, w6: 2.5, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 62
    SmackableDef { name: "smck_block_stone_2x2", mass: 75.0, bounty: 10, smash_threshold: 576.0, explosion: 0.0, restitution: 0.4, w6: 1.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 63
    SmackableDef { name: "smck_block_stone_2x4", mass: 150.0, bounty: 10, smash_threshold: 1152.0, explosion: 0.0, restitution: 0.4, w6: 2.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 64
    SmackableDef { name: "smck_block_stone_2x6", mass: 225.0, bounty: 10, smash_threshold: 1728.0001, explosion: 0.0, restitution: 0.4, w6: 3.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 65
    SmackableDef { name: "smck_block_stone_4x4", mass: 300.0, bounty: 10, smash_threshold: 2304.0, explosion: 0.0, restitution: 0.4, w6: 4.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 66
    SmackableDef { name: "smck_block_stone_4x4Tri", mass: 150.0, bounty: 10, smash_threshold: 1152.0, explosion: 0.0, restitution: 0.4, w6: 2.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 67
    SmackableDef { name: "smck_block_wood_1x4", mass: 50.0, bounty: 10, smash_threshold: 384.0, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 68
    SmackableDef { name: "smck_block_wood_1x8", mass: 100.0, bounty: 10, smash_threshold: 768.0, explosion: 0.0, restitution: 0.7, w6: 2.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 69
    SmackableDef { name: "smck_block_wood_1x10", mass: 125.0, bounty: 10, smash_threshold: 960.0, explosion: 0.0, restitution: 0.7, w6: 2.5, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 70
    SmackableDef { name: "smck_block_wood_2x2", mass: 50.0, bounty: 10, smash_threshold: 384.0, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 71
    SmackableDef { name: "smck_block_wood_2x4", mass: 100.0, bounty: 10, smash_threshold: 768.0, explosion: 0.0, restitution: 0.7, w6: 2.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 72
    SmackableDef { name: "smck_block_wood_2x6", mass: 150.0, bounty: 10, smash_threshold: 1152.0, explosion: 0.0, restitution: 0.7, w6: 3.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 73
    SmackableDef { name: "smck_block_wood_4x4", mass: 200.0, bounty: 10, smash_threshold: 1536.0, explosion: 0.0, restitution: 0.7, w6: 4.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 74
    SmackableDef { name: "smck_block_wood_4x4Tri", mass: 100.0, bounty: 10, smash_threshold: 768.0, explosion: 0.0, restitution: 0.7, w6: 2.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 75
    SmackableDef { name: "smck_dropped_tnt_box", mass: 80.0, bounty: 10, smash_threshold: 120.0, explosion: 40.0, restitution: 0.7, w6: 0.0, car_only: true, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "destructible/vfx_tnt_explosion.xml", sound_type: 5, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 76
    SmackableDef { name: "cannon_ball", mass: 1000.0, bounty: 10, smash_threshold: 600.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Cannon_ball_impact.xml", explosion_fx: "", sound_type: 7, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 77
    SmackableDef { name: "smck_block_glass_3X6_h", mass: 84.375, bounty: 10, smash_threshold: 20250.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 78
    SmackableDef { name: "smck_block_glass_3X6_w", mass: 84.375, bounty: 10, smash_threshold: 20250.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 79
    SmackableDef { name: "smck_block_stone_3X6_h", mass: 253.125, bounty: 10, smash_threshold: 60750.0, explosion: 0.0, restitution: 0.4, w6: 0.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 80
    SmackableDef { name: "smck_block_stone_3X6_w", mass: 253.125, bounty: 10, smash_threshold: 60750.0, explosion: 0.0, restitution: 0.4, w6: 0.0, car_only: false, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 81
    SmackableDef { name: "smck_block_wood_3X6_h", mass: 168.75, bounty: 10, smash_threshold: 40500.0, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 82
    SmackableDef { name: "smck_block_wood_3X6_w", mass: 168.75, bounty: 10, smash_threshold: 40500.0, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 83
    SmackableDef { name: "bombs_bomb", mass: 80.0, bounty: 10, smash_threshold: 60.0, explosion: 40.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "abilities_fx/bomb/black_bossbomb_smoke.xml", sound_type: 6, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 84
    SmackableDef { name: "smck_dropped_glass_2x2", mass: 25.0, bounty: 10, smash_threshold: 96.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: true, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 1, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 85
    SmackableDef { name: "smck_dropped_wood_2x2", mass: 50.0, bounty: 10, smash_threshold: 384.0, explosion: 0.0, restitution: 0.7, w6: 0.0, car_only: true, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 86
    SmackableDef { name: "smck_dropped_stone_2x2", mass: 75.0, bounty: 10, smash_threshold: 576.0, explosion: 0.0, restitution: 0.4, w6: 0.0, car_only: true, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 2, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 87
    SmackableDef { name: "smck_tnt_box_2m", mass: 80.0, bounty: 10, smash_threshold: 2.0, explosion: 40.0, restitution: 0.7, w6: 0.0, car_only: true, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "destructible/vfx_tnt_explosion.xml", sound_type: 5, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 88
    SmackableDef { name: "smck_randompower_box", mass: 25.0, bounty: 10, smash_threshold: 60.0, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: true, smash_fx: "destructible/Glass_impact.xml", explosion_fx: "", sound_type: 8, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 89
    SmackableDef { name: "smck_random_frag", mass: 5.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.2, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 90
    SmackableDef { name: "matildaegg_whole", mass: 84.375, bounty: 10, smash_threshold: 60.0, explosion: 360.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "Abilities_fx/White/White_Ability_EggImpact.xml", sound_type: 10, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 91
    SmackableDef { name: "moustachepig_tnt", mass: 84.375, bounty: 10, smash_threshold: 60.0, explosion: 120.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "", explosion_fx: "Abilities_fx/MoustachePig/MPigAbility_TNT_Impact.xml", sound_type: 5, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 92
    SmackableDef { name: "smck_route_blocker", mass: 100000.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 360.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: true }, // 93
    SmackableDef { name: "smck_blocker_sml", mass: 100000.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 360.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: true }, // 94
    SmackableDef { name: "smck_blocker_lrg", mass: 100000.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 360.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: true }, // 95
    SmackableDef { name: "smck_blocker_seedway2", mass: 100000.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 360.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: true }, // 96
    SmackableDef { name: "smck_blocker_air1_a", mass: 100000.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 360.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: true }, // 97
    SmackableDef { name: "smck_blocker_air1_b", mass: 100000.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 360.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: true }, // 98
    SmackableDef { name: "stellashieldbubble_smack", mass: 25.0, bounty: 10, smash_threshold: 6.0, explosion: 90.0, restitution: 0.7, w6: 0.0, car_only: true, smash_fx: "Abilities_fx/Pink/PinkBossBubbleImpact.xml", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 1, preload: 1, always_collide: false }, // 99
    SmackableDef { name: "boss_terencerocks", mass: 100000.0, bounty: 10, smash_threshold: 60000.0, explosion: 0.0, restitution: 0.9, w6: 0.0, car_only: true, smash_fx: "destructible/Dust_impact.xml", explosion_fx: "", sound_type: 3, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 100
    SmackableDef { name: "boss_bubbles_coins", mass: 5.0, bounty: 10, smash_threshold: 6.0, explosion: 0.0, restitution: 0.0, w6: 25.0, car_only: true, smash_fx: "destructible/CoinBox_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 101
    SmackableDef { name: "boss_bubbles_boost", mass: 5.0, bounty: 10, smash_threshold: 6.0, explosion: 0.0, restitution: 0.0, w6: 25.0, car_only: true, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 102
    SmackableDef { name: "boss_bubbles_tnt", mass: 50.0, bounty: 10, smash_threshold: 60.0, explosion: 100.0, restitution: 0.0, w6: 25.0, car_only: true, smash_fx: "", explosion_fx: "destructible/TNT_explosion.xml", sound_type: 5, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 103
    SmackableDef { name: "boss_moustache_rocket", mass: 10.0, bounty: 10, smash_threshold: 30.0, explosion: 40.0, restitution: 0.0, w6: 0.5, car_only: false, smash_fx: "", explosion_fx: "destructible/TNT_explosion.xml", sound_type: 5, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 104
    SmackableDef { name: "boss_hal_boomerang", mass: 10.0, bounty: 10, smash_threshold: 1.1999999, explosion: 0.0, restitution: 0.7, w6: 0.5, car_only: false, smash_fx: "abilities_fx/hal/HalBossBoomerang_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 105
    SmackableDef { name: "boss_kingsminion", mass: 25.0, bounty: 10, smash_threshold: 12000.0, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 9, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 106
    SmackableDef { name: "smck_blocker_snow_a", mass: 100000.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 360.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: true }, // 107
    SmackableDef { name: "smck_blocker_snow_b", mass: 100000.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 360.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "", sound_type: 4, disable_collisions: 0, w12: 0, preload: 0, always_collide: true }, // 108
    SmackableDef { name: "smck_Slalom_BLUE_LT", mass: 25.0, bounty: 10, smash_threshold: 96.0, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 109
    SmackableDef { name: "smck_Slalom_BLUE_LT_Frag01", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 110
    SmackableDef { name: "smck_Slalom_BLUE_LT_Frag02", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 111
    SmackableDef { name: "smck_Slalom_BLUE_LT_Frag03", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 112
    SmackableDef { name: "smck_Slalom_BLUE_RT", mass: 25.0, bounty: 10, smash_threshold: 96.0, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 113
    SmackableDef { name: "smck_Slalom_BLUE_RT_Frag01", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 114
    SmackableDef { name: "smck_Slalom_BLUE_RT_Frag02", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 115
    SmackableDef { name: "smck_Slalom_BLUE_RT_Frag03", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 116
    SmackableDef { name: "smck_Slalom_RED_LT", mass: 25.0, bounty: 10, smash_threshold: 96.0, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 117
    SmackableDef { name: "smck_Slalom_RED_LT_Frag01", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 118
    SmackableDef { name: "smck_Slalom_RED_LT_Frag02", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 119
    SmackableDef { name: "smck_Slalom_RED_LT_Frag03", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 120
    SmackableDef { name: "smck_Slalom_RED_RT", mass: 25.0, bounty: 10, smash_threshold: 96.0, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 121
    SmackableDef { name: "smck_Slalom_RED_RT_Frag01", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 122
    SmackableDef { name: "smck_Slalom_RED_RT_Frag02", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 123
    SmackableDef { name: "smck_Slalom_RED_RT_Frag03", mass: 25.0, bounty: 10, smash_threshold: f32::INFINITY, explosion: 0.0, restitution: 0.7, w6: 1.0, car_only: false, smash_fx: "", explosion_fx: "", sound_type: 0, disable_collisions: 0, w12: 0, preload: 1, always_collide: false }, // 124
    SmackableDef { name: "smck_TNT_Box_3m", mass: 80.0, bounty: 10, smash_threshold: 900.0, explosion: 80.0, restitution: 0.7, w6: 0.0, car_only: false, smash_fx: "destructible/Wood_impact.xml", explosion_fx: "destructible/vfx_tnt_explosion.xml", sound_type: 5, disable_collisions: 0, w12: 0, preload: 0, always_collide: false }, // 125
];

pub fn def(type_id: u32) -> Option<&'static SmackableDef> {
    SMACKABLES.get(type_id as usize)
}
